name: Java CI with Maven and React with NPM vite

on:
  push:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js for the frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.*'  # Version for React app

    # Install frontend dependencies and build the React app
    - name: Install dependencies and build frontend
      run: |
        cd fullstack-proj-frontend
        npm ci
        npm run build

    # Set up JDK 17 for the backend
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build backend with Maven
    - name: Build backend with Maven
      run: |
        cd fullstack-backend-proj2
        mvn -B package --file pom.xml
        #mvn install -DskipTests #Skip tests for now

